openapi: 3.0.2
info:
  contact:
    email: sig@rennesmetropole.fr
    name: Rennes Metropole - Service Information Géographique
    url: https://public.sig.rennesmetropole.fr/
  description: '''TODO Description'''
  license:
    name: Licence ODbL 1.0
    url: https://opendatacommons.org/licenses/odbl/
  title: RENNES METROPOLE - API 3D
  version: 1.0.0
  x-keywords:
  - geospatial
  - data
  - api
  - rennes metropole
  - 3D
  - CityGML
  - CityJSON
  - Open API Feature
  - OGC
servers:
- description: Serveur de production
  url: https://data.example.org/
- description: Serveur de développement
  url: https://dev.example.org/
tags:
- description: essential characteristics of this API
  name: Capabilities
- description: access to data (features)
  name: Data
paths:
  /:
    get:
      description: The landing page provides links to the API definition and the conformance
        statements for this API.
      operationId: getLandingPage
      parameters:
      - description: The optional f parameter indicates the output format that the
          server shall provide as part of the response document.  The default format
          is JSON.
        explode: false
        in: query
        name: f
        required: false
        schema:
          default: json
          enum:
          - json
          - html
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/landingPage'
            text/html:
              schema:
                type: string
          description: |-
            The landing page provides links to the API definition
            (link relations `service-desc` and `service-doc`),
            and the Conformance declaration (path `/conformance`,
            link relation `conformance`).
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: Not found response.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: Landing page
      tags:
      - Capabilities
      x-eov-operation-handler: controllers/CapabilitiesController
  /conformance:
    get:
      description: A list of all conformance classes specified in a standard that
        the server conforms to.
      operationId: getConformanceDeclaration
      parameters:
      - description: The optional f parameter indicates the output format that the
          server shall provide as part of the response document.  The default format
          is JSON.
        explode: false
        in: query
        name: f
        required: false
        schema:
          default: json
          enum:
          - json
          - html
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
                conformsTo:
                - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core
                - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/landingPage
                - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/oas30
                - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/html
                - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/json
              schema:
                $ref: '#/components/schemas/confClasses'
            text/html:
              schema:
                type: string
          description: |-
            The URIs of all conformance classes supported by the server.

            To support "generic" clients that want to access multiple
            OGC API Features implementations - and not "just" a specific
            API / server, the server declares the conformance
            classes it implements and conforms to.
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: Not found response.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: API conformance definition
      tags:
      - Capabilities
      x-eov-operation-handler: controllers/CapabilitiesController
  /collections:
    get:
      operationId: getCollections
      responses:
        "200":
          content:
            application/json:
              example:
                links:
                - href: http://data.example.org/collections.json
                  rel: self
                  type: application/json
                  title: this document
                - href: http://data.example.org/collections.html
                  rel: alternate
                  type: text/html
                  title: this document as HTML
                - href: http://schemas.example.org/1.0/buildings.xsd
                  rel: describedby
                  type: application/xml
                  title: GML application schema for Acme Corporation building data
                - href: http://download.example.org/buildings.gpkg
                  rel: enclosure
                  type: application/geopackage+sqlite3
                  title: Bulk download (GeoPackage)
                  length: 472546
                collections:
                - id: buildings
                  title: Buildings
                  description: Buildings in the city of Bonn.
                  extent:
                    spatial:
                      bbox:
                      - - 7.01
                        - 50.63
                        - 7.22
                        - 50.78
                    temporal:
                      interval:
                      - - 2010-02-15T12:34:56Z
                        - null
                  links:
                  - href: http://data.example.org/collections/buildings/items
                    rel: items
                    type: application/geo+json
                    title: Buildings
                  - href: http://data.example.org/collections/buildings/items.html
                    rel: items
                    type: text/html
                    title: Buildings
                  - href: https://creativecommons.org/publicdomain/zero/1.0/
                    rel: license
                    type: text/html
                    title: CC0-1.0
                  - href: https://creativecommons.org/publicdomain/zero/1.0/rdf
                    rel: license
                    type: application/rdf+xml
                    title: CC0-1.0
              schema:
                $ref: '#/components/schemas/collections'
            text/html:
              schema:
                type: string
          description: |-
            The feature collections shared by this API.

            The dataset is organized as one or more feature collections. This resource
            provides information about and access to the collections.

            The response contains the list of collections. For each collection, a link
            to the items in the collection (path `/collections/{collectionId}/items`,
            link relation `items`) as well as key information about the collection.
            This information includes:

            * A local identifier for the collection that is unique for the dataset;
            * A list of coordinate reference systems (CRS) in which geometries may be returned by the server. The first CRS is the default coordinate reference system (the default is always WGS 84 with axis order longitude/latitude);
            * An optional title and description for the collection;
            * An optional extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data;
            * An optional indicator about the type of the items in the collection (the default value, if the indicator is not provided, is 'feature').
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: Not found response.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
      summary: the feature collections in the dataset
      tags:
      - Capabilities
      x-eov-operation-handler: controllers/CapabilitiesController
  /raster/elevation/commune/{code_insee}:
    get:
      description: TODO Description
      operationId: rasterElevationCommuneCodeInseeGET
      parameters:
      - explode: false
        in: path
        name: code_insee
        required: true
        schema:
          example: "35238"
          maximum: 1
          minimum: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            image/tiff:
              schema:
                format: binary
                type: string
          description: image de retour
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: Not found response.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
      summary: Terrain en raster d'élévation non texturé
      tags:
      - Data
      x-eov-operation-handler: controllers/DataController
  /raster/elevation/bbox/:
    get:
      description: TODO Description
      operationId: rasterElevationBboxGET
      parameters:
      - explode: false
        in: query
        name: bbox
        required: false
        schema:
          items:
            type: number
          maxItems: 6
          minItems: 4
          type: array
        style: form
      responses:
        "200":
          content:
            image/tiff:
              schema:
                format: binary
                type: string
          description: image de retour
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: Not found response.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
      summary: Terrain en raster d'élévation non texturé
      tags:
      - Data
      x-eov-operation-handler: controllers/DataController
  /batiments/:
    get:
      description: TODO Description
      operationId: batimentsGET
      parameters:
      - explode: false
        in: query
        name: bbox
        required: false
        schema:
          items:
            type: number
          maxItems: 6
          minItems: 4
          type: array
        style: form
      - allowEmptyValue: false
        explode: true
        in: query
        name: texture
        required: true
        schema:
          default: false
          type: boolean
        style: form
      - explode: false
        in: header
        name: format
        required: false
        schema:
          enum:
          - cityJSON
          - CityGML
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: Not found response.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
      summary: Maquette blanche en accès direct (cityJSON, cityGML) sur Bbox
      tags:
      - Data
      x-eov-operation-handler: controllers/DataController
  /batiments/commune/{code_insee}:
    get:
      description: TODO Description
      operationId: batimentsCommuneCodeInseeGET
      parameters:
      - explode: false
        in: path
        name: code_insee
        required: true
        schema:
          example: "35238"
          maximum: 1
          minimum: 1
          type: string
        style: simple
      - allowEmptyValue: false
        explode: true
        in: query
        name: texture
        required: true
        schema:
          default: false
          type: boolean
        style: form
      - explode: false
        in: header
        name: format
        required: false
        schema:
          enum:
          - cityJSON
          - CityGML
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: Not found response.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
      summary: Maquette blanche en accès direct (cityJSON, cityGML) sur code insee
      tags:
      - Data
      x-eov-operation-handler: controllers/DataController
  /batiments/batiment/{id}:
    get:
      description: TODO Description
      operationId: batimentsBatimentIdGET
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      - allowEmptyValue: false
        explode: true
        in: query
        name: texture
        required: true
        schema:
          default: false
          type: boolean
        style: form
      - explode: false
        in: header
        name: format
        required: false
        schema:
          enum:
          - cityJSON
          - CityGML
          type: string
        style: simple
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: Not found response.
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: A server error occurred.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exception'
            text/html:
              schema:
                type: string
          description: General HTTP error response.
      summary: Maquette blanche en accès direct (cityJSON, cityGML) sur id de batiment
      tags:
      - Data
      x-eov-operation-handler: controllers/DataController
components:
  parameters:
    f:
      description: The optional f parameter indicates the output format that the server
        shall provide as part of the response document.  The default format is JSON.
      explode: false
      in: query
      name: f
      required: false
      schema:
        default: json
        enum:
        - json
        - html
        type: string
      style: form
    bbox:
      explode: false
      in: query
      name: bbox
      required: false
      schema:
        items:
          type: number
        maxItems: 6
        minItems: 4
        type: array
      style: form
  responses:
    "200":
      description: successful operation
    wms:
      content:
        image/tiff:
          schema:
            format: binary
            type: string
      description: image de retour
    "400":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception'
        text/html:
          schema:
            type: string
      description: General HTTP error response.
    "404":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception'
        text/html:
          schema:
            type: string
      description: Not found response.
    "500":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception'
        text/html:
          schema:
            type: string
      description: A server error occurred.
    LandingPage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/landingPage'
        text/html:
          schema:
            type: string
      description: |-
        The landing page provides links to the API definition
        (link relations `service-desc` and `service-doc`),
        and the Conformance declaration (path `/conformance`,
        link relation `conformance`).
    ConformanceDeclaration:
      content:
        application/json:
          example:
            conformsTo:
            - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core
            - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/landingPage
            - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/oas30
            - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/html
            - http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/json
          schema:
            $ref: '#/components/schemas/confClasses'
        text/html:
          schema:
            type: string
      description: |-
        The URIs of all conformance classes supported by the server.

        To support "generic" clients that want to access multiple
        OGC API Features implementations - and not "just" a specific
        API / server, the server declares the conformance
        classes it implements and conforms to.
  schemas:
    landingPage:
      example:
        description: description
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/json
          title: Trierer Strasse 70, 53115 Bonn
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/json
          title: Trierer Strasse 70, 53115 Bonn
        title: Buildings in Bonn
      properties:
        title:
          example: Buildings in Bonn
          type: string
        description:
          type: string
        links:
          items:
            $ref: '#/components/schemas/link'
          type: array
      required:
      - links
      type: object
    link:
      example:
        hreflang: en
        rel: alternate
        length: 0
        href: http://data.example.com/buildings/123
        type: application/json
        title: Trierer Strasse 70, 53115 Bonn
      properties:
        href:
          example: http://data.example.com/buildings/123
          type: string
        rel:
          example: alternate
          type: string
        type:
          example: application/json
          type: string
        hreflang:
          example: en
          type: string
        title:
          example: Trierer Strasse 70, 53115 Bonn
          type: string
        length:
          type: integer
      required:
      - href
      - rel
      type: object
    exception:
      description: JSON schema for exceptions based on RFC 7807
      example:
        instance: instance
        detail: detail
        type: type
        title: title
        status: 0
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
      required:
      - type
      type: object
    confClasses:
      example:
        conformsTo:
        - conformsTo
        - conformsTo
      properties:
        conformsTo:
          items:
            type: string
          type: array
      required:
      - conformsTo
      type: object
    collections:
      example:
        collections:
        - extent:
            spatial:
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              bbox:
              - - -180
                - -90
                - 180
                - 90
              - - -180
                - -90
                - 180
                - 90
            temporal:
              trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
              interval:
              - - 2011-11-11T12:22:11Z
                - null
              - - 2011-11-11T12:22:11Z
                - null
          itemType: feature
          crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/4326
          description: An address.
          links:
          - href: http://data.example.com/buildings
            rel: item
          - href: http://example.com/concepts/buildings.html
            rel: describedby
            type: text/html
          id: address
          title: address
        - extent:
            spatial:
              crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
              bbox:
              - - -180
                - -90
                - 180
                - 90
              - - -180
                - -90
                - 180
                - 90
            temporal:
              trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
              interval:
              - - 2011-11-11T12:22:11Z
                - null
              - - 2011-11-11T12:22:11Z
                - null
          itemType: feature
          crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/4326
          description: An address.
          links:
          - href: http://data.example.com/buildings
            rel: item
          - href: http://example.com/concepts/buildings.html
            rel: describedby
            type: text/html
          id: address
          title: address
        links:
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
        - hreflang: en
          rel: alternate
          length: 0
          href: http://data.example.com/buildings/123
          type: application/geo+json
          title: Trierer Strasse 70, 53115 Bonn
      properties:
        links:
          items:
            $ref: '#/components/schemas/link_1'
          type: array
        collections:
          items:
            $ref: '#/components/schemas/collection'
          type: array
      required:
      - collections
      - links
      type: object
    link_1:
      example:
        hreflang: en
        rel: alternate
        length: 0
        href: http://data.example.com/buildings/123
        type: application/geo+json
        title: Trierer Strasse 70, 53115 Bonn
      properties:
        href:
          example: http://data.example.com/buildings/123
          type: string
        rel:
          example: alternate
          type: string
        type:
          example: application/geo+json
          type: string
        hreflang:
          example: en
          type: string
        title:
          example: Trierer Strasse 70, 53115 Bonn
          type: string
        length:
          type: integer
      required:
      - href
      type: object
    collection:
      example:
        extent:
          spatial:
            crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            bbox:
            - - -180
              - -90
              - 180
              - 90
            - - -180
              - -90
              - 180
              - 90
          temporal:
            trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
            interval:
            - - 2011-11-11T12:22:11Z
              - null
            - - 2011-11-11T12:22:11Z
              - null
        itemType: feature
        crs:
        - http://www.opengis.net/def/crs/OGC/1.3/CRS84
        - http://www.opengis.net/def/crs/EPSG/0/4326
        description: An address.
        links:
        - href: http://data.example.com/buildings
          rel: item
        - href: http://example.com/concepts/buildings.html
          rel: describedby
          type: text/html
        id: address
        title: address
      properties:
        id:
          description: identifier of the collection used, for example, in URIs
          example: address
          type: string
        title:
          description: human readable title of the collection
          example: address
          type: string
        description:
          description: a description of the features in the collection
          example: An address.
          type: string
        links:
          example:
          - href: http://data.example.com/buildings
            rel: item
          - href: http://example.com/concepts/buildings.html
            rel: describedby
            type: text/html
          items:
            $ref: '#/components/schemas/link_1'
          type: array
        extent:
          $ref: '#/components/schemas/extent'
        itemType:
          default: feature
          description: indicator about the type of the items in the collection (the
            default value is 'feature').
          type: string
        crs:
          default:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          description: the list of coordinate reference systems supported by the service
          example:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/4326
          items:
            type: string
          type: array
      required:
      - id
      - links
      type: object
    extent:
      description: |-
        The extent of the features in the collection. In the Core only spatial and temporal
        extents are specified. Extensions may add additional members to represent other
        extents, for example, thermal or pressure ranges.
      example:
        spatial:
          crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
          bbox:
          - - -180
            - -90
            - 180
            - 90
          - - -180
            - -90
            - 180
            - 90
        temporal:
          trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          interval:
          - - 2011-11-11T12:22:11Z
            - null
          - - 2011-11-11T12:22:11Z
            - null
      properties:
        spatial:
          $ref: '#/components/schemas/extent_spatial'
        temporal:
          $ref: '#/components/schemas/extent_temporal'
      type: object
    exception_1:
      description: 'Information about the exception: an error code plus an optional
        description.'
      properties:
        code:
          type: string
        description:
          type: string
      required:
      - code
      type: object
    extent_spatial:
      description: The spatial extent of the features in the collection.
      example:
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        bbox:
        - - -180
          - -90
          - 180
          - 90
        - - -180
          - -90
          - 180
          - 90
      properties:
        bbox:
          description: |-
            One or more bounding boxes that describe the spatial extent of the dataset.
            In the Core only a single bounding box is supported. Extensions may support
            additional areas. If multiple areas are provided, the union of the bounding
            boxes describes the spatial extent.
          items:
            description: |-
              Each bounding box is provided as four or six numbers, depending on
              whether the coordinate reference system includes a vertical axis
              (height or depth):

              * Lower left corner, coordinate axis 1
              * Lower left corner, coordinate axis 2
              * Minimum value, coordinate axis 3 (optional)
              * Upper right corner, coordinate axis 1
              * Upper right corner, coordinate axis 2
              * Maximum value, coordinate axis 3 (optional)

              The coordinate reference system of the values is WGS 84 longitude/latitude
              (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate
              reference system is specified in `crs`.

              For WGS 84 longitude/latitude the values are in most cases the sequence of
              minimum longitude, minimum latitude, maximum longitude and maximum latitude.
              However, in cases where the box spans the antimeridian the first value
              (west-most box edge) is larger than the third value (east-most box edge).

              If the vertical axis is included, the third and the sixth number are
              the bottom and the top of the 3-dimensional bounding box.

              If a feature has multiple spatial geometry properties, it is the decision of the
              server whether only a single spatial geometry property is used to determine
              the extent or all relevant geometries.
            example:
            - -180
            - -90
            - 180
            - 90
            items:
              type: number
            type: array
          minItems: 1
          type: array
        crs:
          default: http://www.opengis.net/def/crs/OGC/1.3/CRS84
          description: |-
            Coordinate reference system of the coordinates in the spatial extent
            (property `bbox`). The default reference system is WGS 84 longitude/latitude.
            In the Core this is the only supported coordinate reference system.
            Extensions may support additional coordinate reference systems and add
            additional enum values.
          enum:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          type: string
      type: object
    extent_temporal:
      description: The temporal extent of the features in the collection.
      example:
        trs: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
        interval:
        - - 2011-11-11T12:22:11Z
          - null
        - - 2011-11-11T12:22:11Z
          - null
      properties:
        interval:
          description: |-
            One or more time intervals that describe the temporal extent of the dataset.
            The value `null` is supported and indicates an unbounded interval end.
            In the Core only a single time interval is supported. Extensions may support
            multiple intervals. If multiple intervals are provided, the union of the
            intervals describes the temporal extent.
          items:
            description: |-
              Begin and end times of the time interval. The timestamps are in the
              temporal coordinate reference system specified in `trs`. By default
              this is the Gregorian calendar.
            example:
            - 2011-11-11T12:22:11Z
            - null
            items:
              format: date-time
              nullable: true
              type: string
            maxItems: 2
            minItems: 2
            type: array
          minItems: 1
          type: array
        trs:
          default: http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          description: |-
            Coordinate reference system of the coordinates in the temporal extent
            (property `interval`). The default reference system is the Gregorian calendar.
            In the Core this is the only supported temporal coordinate reference system.
            Extensions may support additional temporal coordinate reference systems and add
            additional enum values.
          enum:
          - http://www.opengis.net/def/uom/ISO-8601/0/Gregorian
          type: string
      type: object
